name: pre-commit

on:
  pull_request:
  push:
    branches: [main]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: |
         sudo apt update
         sudo apt install gcc-10 make valgrind
      shell: bash
    - uses: actions/setup-python@v3
    - uses: pre-commit/action@v3.0.1
